/* Generated By:JJTree: Do not edit this line. ASTArguments.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArguments extends SimpleNode {
  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6b699127195b9432dc7fbeea459c60d (do not edit this line) */
