/* Generated By:JJTree: Do not edit this line. ASTAfterIdentifier.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAfterIdentifier extends SimpleNode {
  public ASTAfterIdentifier(int id) {
    super(id);
  }

  public ASTAfterIdentifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d71d63600b2e44caa2bbe5c8b037538 (do not edit this line) */
