/* Generated By:JJTree: Do not edit this line. ASTArrayInitializer.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayInitializer extends SimpleNode {
  public ASTArrayInitializer(int id) {
    super(id);
  }

  public ASTArrayInitializer(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fcf737945fee5dda6cb589ae9526939d (do not edit this line) */
