/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1331f3a4abb41dd7441a4ad2967e1ef3 (do not edit this line) */
