/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBlockStatement extends SimpleNode {
  public ASTBlockStatement(int id) {
    super(id);
  }

  public ASTBlockStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5a694c0a249c9340c93741947532cba (do not edit this line) */
