/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf897f53df4ea041d1816f03d3a2c335 (do not edit this line) */
