/* Generated By:JJTree: Do not edit this line. ASTConditionalAndExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionalAndExpression extends SimpleNode {
  public ASTConditionalAndExpression(int id) {
    super(id);
  }

  public ASTConditionalAndExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e8bb25d7fe7fea99ffaf65e0073ef01d (do not edit this line) */
