/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=849b020f1d4c29c6ccd795490d3387c4 (do not edit this line) */
