/* Generated By:JJTree: Do not edit this line. ASTIdentifierStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifierStatement extends SimpleNode {
  public ASTIdentifierStatement(int id) {
    super(id);
  }

  public ASTIdentifierStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7229d7af4f0d7b2dc24c5f396fa246b (do not edit this line) */
