/* Generated By:JJTree: Do not edit this line. ASTInsideArray.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInsideArray extends SimpleNode {
  public ASTInsideArray(int id) {
    super(id);
  }

  public ASTInsideArray(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97b7c168d68686d1daf15fb8b67585bb (do not edit this line) */
