/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportDeclaration extends SimpleNode {
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7fa7f9841bfefec4d3c2ddf101a4634 (do not edit this line) */
