/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLiteral extends SimpleNode {
  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4448992edd7c7fc2e96190e85e361107 (do not edit this line) */
