/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLocalVariableDeclaration extends SimpleNode {
  public ASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public ASTLocalVariableDeclaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a2d7b5dcb33f3bc25c849d1f5177d0d (do not edit this line) */
