/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationBody.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodDeclarationBody extends SimpleNode {
  public ASTMethodDeclarationBody(int id) {
    super(id);
  }

  public ASTMethodDeclarationBody(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aaa04e139bc47709431f56ea52448ff7 (do not edit this line) */
