/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultiplicativeExpression extends SimpleNode {
  public ASTMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTMultiplicativeExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=833665594467731ea06acbfc185a038a (do not edit this line) */
