/* Generated By:JJTree: Do not edit this line. ASTName.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae474508796f1b051b5423afeda0f3d3 (do not edit this line) */
