/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimaryPrefix extends SimpleNode {
  public ASTPrimaryPrefix(int id) {
    super(id);
  }

  public ASTPrimaryPrefix(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=249320f155fe67fdb5ccdc84a2364ac3 (do not edit this line) */
