/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=642def8c8ac757207fb51575d918a6f4 (do not edit this line) */
