/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimitiveType extends SimpleNode {
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9fafa3941ea028cb87dd0233b8796761 (do not edit this line) */
