/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatement extends SimpleNode {
  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b4fbb36c8985234e80150f3c704d4a5 (do not edit this line) */
