/* Generated By:JJTree: Do not edit this line. ASTUnaryExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTUnaryExpression extends SimpleNode {
  public ASTUnaryExpression(int id) {
    super(id);
  }

  public ASTUnaryExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=238fd5da7fabb6fab88a8f8c64ce6310 (do not edit this line) */
