/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b24f4b7d6a879f52c994230e35106e08 (do not edit this line) */
