/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ac64872f199f1b839b86eef861ca002 (do not edit this line) */
