/* Generated By:JJTree: Do not edit this line. ASTVariableInitializer.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableInitializer extends SimpleNode {
  public ASTVariableInitializer(int id) {
    super(id);
  }

  public ASTVariableInitializer(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ec879b429ef6175a12b9d372c0c85cd (do not edit this line) */
