/* Generated By:JJTree: Do not edit this line. ASTWhileCondition.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileCondition extends SimpleNode {
  public ASTWhileCondition(int id) {
    super(id);
  }

  public ASTWhileCondition(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=98903e11fc4f5499e34bab0c1979e4d7 (do not edit this line) */
