/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.4 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTNAME = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTIDENTIFIER = 6;
  public int JJTMETHODDECLARATIONBODY = 7;
  public int JJTBLOCKSTATEMENT = 8;
  public int JJTLOCALVARIABLEDECLARATION = 9;
  public int JJTTYPE = 10;
  public int JJTPRIMITIVETYPE = 11;
  public int JJTVARIABLEDECLARATOR = 12;
  public int JJTVARIABLEDECLARATORID = 13;
  public int JJTVARIABLEINITIALIZER = 14;
  public int JJTARRAYINITIALIZER = 15;
  public int JJTEXPRESSION = 16;
  public int JJTCONDITIONALANDEXPRESSION = 17;
  public int JJTRELATIONALEXPRESSION = 18;
  public int JJTADDITIVEEXPRESSION = 19;
  public int JJTMULTIPLICATIVEEXPRESSION = 20;
  public int JJTUNARYEXPRESSION = 21;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 22;
  public int JJTPRIMARYEXPRESSION = 23;
  public int JJTPRIMARYPREFIX = 24;
  public int JJTPRIMARYSUFFIX = 25;
  public int JJTLITERAL = 26;
  public int JJTBOOLEANLITERAL = 27;
  public int JJTARGUMENTS = 28;
  public int JJTARGUMENTLIST = 29;
  public int JJTALLOCATIONEXPRESSION = 30;
  public int JJTINSIDEARRAY = 31;
  public int JJTSTATEMENT = 32;
  public int JJTIFSTATEMENT = 33;
  public int JJTWHILESTATEMENT = 34;
  public int JJTWHILECONDITION = 35;
  public int JJTIDENTIFIERSTATEMENT = 36;
  public int JJTAFTERIDENTIFIER = 37;
  public int JJTERROR_SKIPTO = 38;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "Name",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "Identifier",
    "MethodDeclarationBody",
    "BlockStatement",
    "LocalVariableDeclaration",
    "Type",
    "PrimitiveType",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInitializer",
    "Expression",
    "ConditionalAndExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "UnaryExpressionNotPlusMinus",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "BooleanLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "InsideArray",
    "Statement",
    "IfStatement",
    "WhileStatement",
    "WhileCondition",
    "IdentifierStatement",
    "AfterIdentifier",
    "error_skipto",
  };
}
/* JavaCC - OriginalChecksum=ebf1228879d4c5e749e9e5fc20da6503 (do not edit this line) */
